Created heroes editor
ericchen94/angular-tour-of-heroes pull request #3
Opened 2021-04-08 23:14 UTC by ericchen94

Generate a new hero component and interface to show hero id and name data. Add a textbox to edit the hero's name in real time and in uppercase letters.

2021-04-09 13:52 UTC, rhollinger requested changes
Can you add a `.gitignore` file ([link](https://git-scm.com/docs/gitignore)) and make sure that no compiled files make it into the repo?

2021-04-09 19:13 UTC, ericchen94 commented
Accidentally closed the branch - please ignore

2021-04-09 19:28 UTC, rhollinger requested changes
Can you `git rm` the files you already added that are now blocked by the .gitignore? It will prevent new files from going in, but if they were already checking in they won't get removed automatically. 

When you are done the `Files Changed` part should be only actual code files/configuration you intend to check-in. 

It's just impossible to review 345 files with. 12,000 lines of code change 😃

2021-04-12 21:03 UTC, rhollinger approved these changes

2021-04-12 21:05 UTC, merged